### ISSUE TITLE
--configfile uses absolute path when executing on GSL which causes jobs to fail

### ISSUE THREAD

**Issue by cademirch** [snakemake/snakemake#1833]
**Snakemake version**

`7.12`
**Describe the bug**

When executing a workflow using the `--configfile` and `--google-lifesciences`, Snakemake uses the absolute path of the config file specified when running the cloud jobs. This is problematic because the cloud jobs have a different directory structure and thus the config file is not found. 
**Logs**

Command:
 ```
snakemake --snakefile workflow/Snakefile --default-remote-prefix snakemake/test --profile profiles/gls --configfile config/test_config.yaml
```

Error (from GSL logs):
```
FileNotFoundError: [Errno 2] No such file or directory: '/data/gsl_workflow/config/test_config.yaml'
```
**Minimal example**

**Additional context**

**Comment by drneavin** [comment]
I am experiencing the same issue and have tested with both 7.12 and 7.14. Have you been able to find a method resolve this?

**Comment by drneavin** [comment]
For anyone else struggling with this issue, I've found a temporary work-around. You can pass the config file to snakemake within the Snakefile
The snakemake command would look like:

```
snakemake \
    --snakefile Snakefile \
	--config config_file=config.yaml \
    --rerun-incomplete \
    --jobs 20 \
    --use-singularity \
    --keep-going \
    --google-lifesciences \
    --default-remote-prefix snakemake-test-cloud2 \
    --use-conda \
    --google-lifesciences-region us-west1
```

Then in the Snakefile:
```
configfile: config['config_file']
```

Then `config` can be used as normal. Hopefully the path issues will get resolved in future releases so can be directly used with `--configfile`

**Comment by drneavin** [comment]
Thanks @cademirch! Unfortunately, I'm not very familiar with the snakemake base code so I'm a bit uncomfortable trying to script a fix. So I'll leave it to you or anyone else who happens upon this issue and has more comfort with working with the snakemake base code.

**Comment by fgvieira** [comment]
@drneavin and @cademirch, does this issue persists in snakemake 8?

**Comment by cademirch** [comment]
@fgvieira I haven't tested, but I assume so since the logic handling config files is the same:
https://github.com/snakemake/snakemake/blob/74627d3f07f549600dc8ad226a545f44191141e0/snakemake/settings.py#L328-L329

**Comment by drneavin** [comment]
I've also not tested in 8 and don't currently have any GSL projects ongoing. But I would assume that what @cademirch pointed out is true, that the logic causing the issue is still in place in Snakemake 8

**Comment by schnea** [comment]
`--google-lifesciences` cli option no longer exists
