### ISSUE TITLE
using google life sciences backend raises MissingInputException

### ISSUE THREAD

**Issue by aryam7** [snakemake/snakemake#546]
**Snakemake version**
5.20.1

**Describe the bug**
I see MissingInputException errors whenever attempting to run workflows via the Google Life Sciences Executor.

**Logs**
```
(snakemake) $ snakemake --google-lifesciences --default-remote-prefix snakemake-tutorial-data --use-conda --google-lifesciences-region us-west1
Building DAG of jobs...
MissingInputException in line 7 of Snakefile:
Missing input files for rule bwa_map:
snakemake-tutorial-data/genome.fa.amb
snakemake-tutorial-data/samples/A.fastq
snakemake-tutorial-data/genome.fa.pac
snakemake-tutorial-data/genome.fa.ann
snakemake-tutorial-data/genome.fa.bwt
snakemake-tutorial-data/genome.fa.sa
```

**Example 1**
Follow the steps in [the Google Life Sciences tutorial](https://snakemake.readthedocs.io/en/v5.20.1/executor_tutorial/google_lifesciences.html). I did a few things differently from the tutorial:
1. I cloned [this branch](https://github.com/snakemake/snakemake-tutorial-data/tree/add/upload-google-storage-script) instead of master, since [the pull request for the code used in the tutorial](https://github.com/snakemake/snakemake-tutorial-data/pull/1) has not been approved yet.
```
git clone -b 'add/upload-google-storage-script' https://github.com/snakemake/snakemake-tutorial-data
```
2. I named my bucket `snakemake-tutorial-data` instead of `snakemake-testing-data`, since the `snakemake-testing-data` name was already taken.
3. I created the `Snakefile` and `plot-quals.py` script within the cloned directory (ie the parent of `data/`). The tutorial did not seem to explicitly specify where these should be created, but I couldn't really see any other reasonable alternatives.
4. I fixed the indentation on lines 11-14 of the tutorial's Snakefile.

I also tried moving the files within `data/` to the same directory as the Snakefile. This did not fix the problem.

**Example 2**
Try the same steps as those in Example 1 but create the Snakefile from [this code](https://snakemake.readthedocs.io/en/v5.20.1/tutorial/basics.html#summary) instead of the one in the Google Life Sciences Executor tutorial. I encounter a similar exception:
```
(snakemake) $ snakemake --google-lifesciences --default-remote-prefix snakemake-tutorial-data --use-conda --google-lifesciences-region us-west1
Building DAG of jobs...
MissingInputException in line 9 of Snakefile:
Missing input files for rule bwa_map:
snakemake-tutorial-data/data/samples/A.fastq
snakemake-tutorial-data/data/genome.fa
```

**Additional context**
Inspection of the storage bucket seems to indicate that running `python upload_google_storage.py snakemake-testing-data data/` creates a `data/` folder inside the storage bucket:
![image](https://user-images.githubusercontent.com/23412689/89744121-e1e6c600-da5e-11ea-8eb9-a2dda7de6e68.png)
And this is what it looks like inside the `data/` folder:
![image](https://user-images.githubusercontent.com/23412689/89744185-56216980-da5f-11ea-8bf9-0847d4fafd5c.png)

**Comment by aryam7** [comment]
**Example 3**
Try wrapping the input in the Snakefile with `GS.remote()`. Here's the log output I got with the MissingInputException:
```
(snakemake) $ gsutil ls gs://snakemake-tutorial-data/data/*
gs://snakemake-tutorial-data/data/genome.fa
gs://snakemake-tutorial-data/data/genome.fa.amb
gs://snakemake-tutorial-data/data/genome.fa.ann
gs://snakemake-tutorial-data/data/genome.fa.bwt
gs://snakemake-tutorial-data/data/genome.fa.fai
gs://snakemake-tutorial-data/data/genome.fa.pac
gs://snakemake-tutorial-data/data/genome.fa.sa

gs://snakemake-tutorial-data/data/samples/:
gs://snakemake-tutorial-data/data/samples/A.fastq
gs://snakemake-tutorial-data/data/samples/B.fastq
gs://snakemake-tutorial-data/data/samples/C.fastq
(snakemake) $ snakemake --google-lifesciences --default-remote-prefix snakemake-tutorial-data --use-conda --google-lifesciences-region us-west1
Building DAG of jobs...
MissingInputException in line 10 of Snakefile:
Missing input files for rule bwa_map:
snakemake-tutorial-data/data/genome.fa.pac
snakemake-tutorial-data/data/genome.fa.ann
snakemake-tutorial-data/data/genome.fa.bwt
snakemake-tutorial-data/data/samples/A.fastq
snakemake-tutorial-data/data/genome.fa.sa
snakemake-tutorial-data/data/genome.fa.amb
```
And here's the new Snakefile:
```
from snakemake.remote.GS import RemoteProvider as GSRemoteProvider
GS = GSRemoteProvider()

SAMPLES = ["A", "B"]

rule all:
    input:
        "plots/quals.svg"

rule bwa_map:
    input:
        fastq=GS.remote("snakemake-tutorial-data/data/samples/{sample}.fastq"),
        idx=[GS.remote("snakemake-tutorial-data/data/"+f) for f in multiext("genome.fa", ".amb", ".ann", ".bwt", ".pac", ".sa")]
    conda:
        "environment.yml"
    output:
        "mapped_reads/{sample}.bam"
    params:
        idx=lambda w, input: os.path.splitext(input.idx[0])[0]
    shell:
        "bwa mem {params.idx} {input.fastq} | samtools view -Sb - > {output}"

rule samtools_sort:
    input:
        "mapped_reads/{sample}.bam"
    output:
        "sorted_reads/{sample}.bam"
    conda:
        "environment.yml"
    shell:
        "samtools sort -T sorted_reads/{wildcards.sample} "
        "-O bam {input} > {output}"

rule samtools_index:
    input:
        "sorted_reads/{sample}.bam"
    output:
        "sorted_reads/{sample}.bam.bai"
    conda:
        "environment.yml"
    shell:
        "samtools index {input}"

rule bcftools_call:
    input:
        fa=GS.remote("snakemake-tutorial-data/data/genome.fa"),
        bam=expand("sorted_reads/{sample}.bam", sample=SAMPLES),
        bai=expand("sorted_reads/{sample}.bam.bai", sample=SAMPLES)
    output:
        "calls/all.vcf"
    conda:
        "environment.yml"
    shell:
        "samtools mpileup -g -f {input.fa} {input.bam} | "
        "bcftools call -mv - > {output}"

rule plot_quals:
    input:
        "calls/all.vcf"
    output:
        "plots/quals.svg"
    conda:
        "environment.yml"
    script:
        "plot-quals.py"
```

**Comment by emattei** [comment]
Hi, 
I am facing the exact same issue and I noticed something strange. Apparently, if you remove all the relative path from the output -going from "mapped_reads/{sample}.bam" to "{sample}.bam"- the workflow runs fine. So it's not a mere problem of communicating with the bucket or permissions.

**Comment by vsoch** [comment]
Thanks for reporting this @emattei and @aryam7! It looks a lot like https://hub.docker.com/r/snakemake/snakemake/tags and we think there is an issue with raising the error for output (which should not happen!) I'm going to start to debug this today, and hopefully will figure something out. Thanks for your detailed steps to reproduce!

**Comment by vsoch** [comment]
hey guys! So I think I have the issue figured out, and I'll walk through my debugging here to help. The PR was fairly simple, you can see the fix in https://github.com/snakemake/snakemake/pull/548 (pending random Windows / conda errors). First @aryam7 there was a bug in the upload script that added an extra data to the path - that shouldn't have happened. so If you did:

```bash
python upload_google_storage.py snakemake-testing-data data
```
It should have uploaded data/ on the local machine to the storage root. This should have uploaded to a subfolder called data.

```bash
python upload_google_storage.py snakemake-testing-data/data data
```

That should be fixed now in the branch you cloned. But regardless, the subfolder of data should have worked! So I stepped through the pipeline you gave to reproduce. Note that you shouldn't need to hard code the storage prefix into the path - that would defeat the purpose of being able to specify it on the command line! So I used the regular Snakefile from the tutorial here https://snakemake.readthedocs.io/en/v5.20.1/executor_tutorial/google_lifesciences.html.

## Bug Hypothesis!
The bug is fairly simple, and related to #511 but not an issue with the list_blobs method. The cache for files (local and remote) you can view like a dictionary. In the case of a remote path, we index by the bucket root so that we know we've indexed the bucket (or not). So when we were running list_blobs() for a bucket _subfolder_, even though we might only be indexing a path like `data/plots` (possibly an output file) in fact we were indexing for the root bucket name, regardless of the subfolder, like this:

```python
cache.has_inventory.add(self.bucket_name)
```
And then on a second time around, perhaps when we are checking another file in data/reads, we see that the bucket root name is in the cache and skip over it. What we actually wanted to do in that function is index by the subfolder we've searched, logically:

```python
cache.has_inventory.add("%s/%s" %(self.bucket_name, subfolder))
```

The reason that this spits out a MissingInputException is because the iocache wrapper is returning an incorrect result based on this bug. Let's walk through an example of a file that exists in the bucket, but is returning False that it doesn't exist.

```python
file
'snakemake-testing-data/data/samples/A.fastq'
```

We can see that it is remote, in a Google Storage bucket

```python
file.is_remote
<snakemake.remote.GS.RemoteObject at 0x7ffafc0d95b0>
```

We can also directly interact with that object to verify it exists (this is a Google Storage Python client function)
```python
file.is_remote.exists()
True
```

But for some reason, when we use the file.exists_remote wrapper, which is triggered by the exists function (the one returning False) it's returning False.

```python
if file.is_remote:
    print(file.exists_remote)
False
```

But this doesn't make sense, because if we grab the code in the exists_remote function and run it - it should return True! We skip the first if condition and return self.remote_object.exists() (which is True!)

```python
    @property
    @iocache
    def exists_remote(self):
        if not self.is_remote:
            return False
        return self.remote_object.exists()
```
That's what led me to the iocache wrapper.  Let's walk through that. It looks like we normalize the file name

```python
normalized
'snakemake-testing-data/data/genome.fa.amb'
```

and then check if it's in the cache. This returns True:

```python
normalized in cache
True
```

Logically we could then return it. But when we index normalized in the cache, it's actually not there, and it returns False:

```python
cache[normalized]
False
```

Derp, this shouldn't happen! The reason the first returns true is because the remote bucket is in our inventory (this function checks for the root bucket), e.g., `snakemake-testing-data`

```python
cache.cache.in_inventory(normalized)
True
```

And although the bucket name is indexed, because of the inventory bug, we haven't actually cached the file in it (otherwise it would return something other than False). What _should_ happen here is one of two things:

1. To see that normalized isn't in the cache, and to return the function call, which is the exists_remote (that returns True)
```python
func
<function snakemake.io._IOFile.exists_remote(self)>
v = func(self, *args, **kwargs)
cache[normalized] = v
v
True
```

OR that normalized is in the cache, and we return "True" from the cache instead of False. But neither of those things happen - we see that normalized is in the cache (based on bucket name) but isn't actually there. Because we never cached it. Because we used the wrong index.

The reason we didn't catch in the testing pipeline is because we do everything from the root bucket. This is also why if you change the index to the root bucket, it will actually cache everything (even though this isn't a good strategy to take generally because the user might not want us to index beyond the subfolder they are using, or in the case of public Google buckets, it would be hugely overkill).

It looks like we haven't released a container with the crc32c fix, so although I'm able to skip over the MissingInputException, I can't fully test the updated pipeline with a subfolder. But anyway, I think at least we've made good progress on the issue here! Johannes is in Germany (later there now) so he will likely be able to review/comment sometime this week. Thanks again for your reports!

**Comment by emattei** [comment]
@vsoch thank you very much for taking the time and describe the error and the fix.
I tried the fix and indeed the workflow starts. But, after the docker is downloaded and the data copied, the error persists.
This is the output of `gcloud beta lifesciences operations describe`
```
- containerStopped:
      actionId: 1
      exitStatus: 1
      stderr: |
        --2020-08-10 19:21:04--  https://gist.githubusercontent.com/vsoch/84886ef6469bedeeb9a79a4eb7aec0d1/raw/181499f8f17163dcb2f89822079938cbfbd258cc/download.py
        Resolving gist.githubusercontent.com (gist.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
        Connecting to gist.githubusercontent.com (gist.githubusercontent.com)|151.101.0.133|:443... connected.
        HTTP request sent, awaiting response... 200 OK
        Length: 1246 (1.2K) [text/plain]
        Saving to: ‘/download.py’

             0K .                                                     100% 54.1M=0s

        2020-08-10 19:21:04 (54.1 MB/s) - ‘/download.py’ saved [1246/1246]

        Building DAG of jobs...
        MissingInputException in line 7 of /workdir/Snakefile:
        Missing input files for rule bwa_map:
        snakemake/data/genome.fa.sa
        snakemake/data/genome.fa.ann
        snakemake/data/genome.fa.pac
        snakemake/data/genome.fa.amb
        snakemake/data/genome.fa.bwt
    description: |-
      Stopped running "snakejob-bwa_map-4": exit status 1: --2020-08-10 19:21:04--  https://gist.githubusercontent.com/vsoch/84886ef6469bedeeb9a79a4eb7aec0d1/raw/181499f8f17163dcb2f89822079938cbfbd258cc/download.py
      Resolving gist.githubusercontent.com (gist.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
      Connecting to gist.githubusercontent.com (gist.githubusercontent.com)|151.101.0.133|:443... connected.
      HTTP request sent, awaiting response... 200 OK
      Length: 1246 (1.2K) [text/plain]
      Saving to: ‘/download.py’

           0K .                                                     100% 54.1M=0s

      2020-08-10 19:21:04 (54.1 MB/s) - ‘/download.py’ saved [1246/1246]

      Building DAG of jobs...
      MissingInputException in line 7 of /workdir/Snakefile:
      Missing input files for rule bwa_map:
      snakemake/data/genome.fa.sa
      snakemake/data/genome.fa.ann
      snakemake/data/genome.fa.pac
      snakemake/data/genome.fa.amb
      snakemake/data/genome.fa.bwt
    timestamp: '2020-08-10T19:21:12.709621981Z'
```
So, the MissingInputException remain even if the data is right there 
![image](https://user-images.githubusercontent.com/13934804/89822189-ce4e6480-db1d-11ea-935f-ee278e2de3f8.png)

**Comment by vsoch** [comment]
@emattei the container that is being used with snakemake would still have this bug.

**Comment by emattei** [comment]
@vsoch oops, yes I forgot about that...

**Comment by vsoch** [comment]
haha totally no worries - I do that too! :) What you could try (I haven't done this before but don't see why it wouldn't work) is to build and push your own container from the branch you cloned with the fix:

```bash
docker build -t <myusername>/snakemake:test .
docker push <myusername>/snakemake:test
```
And then set that as the `--container` argument:

```bash
snakemake ... --container <myusername>/snakemake:test
```
If getting this running is super urgent for you! It would also greatly help with testing of course!

**Comment by emattei** [comment]
@vsoch sorry it took me a little bit of time but I did it and it worked!
![image](https://user-images.githubusercontent.com/13934804/89831609-20968200-db2c-11ea-99fb-297d1f1498cd.png)

**Comment by vsoch** [comment]
yay!! You just made my day!! :D

**Comment by emattei** [comment]
well, thank you for fixing it!

**Comment by aryam7** [comment]
@vsoch and @emattei Thank you for all of your work! And thank you for the fascinating explanation of the bug, @vsoch!

**Comment by aryam7** [comment]
I'm closing this because it seems like everything is resolved. Feel free to reopen, if not.

I ran into a couple other problems with the tutorial, but they were mostly small things (ie indentation on some lines + some other changes I had to make to the Snakefile).

**Comment by vsoch** [comment]
Thanks @aryam7 ! Definitely those indentation issues are bugs - I opened a PR yesterday to fix but it hasn't been merged yet, but hopefully soon: https://github.com/snakemake/snakemake/pull/553.
